name: Github, Vault and TFC Demo

on:
  push:
    tags:
      - "v[0-9]"

jobs:
  demo:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Get Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.5.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          role: demo-role
          method: jwt
          namespace: admin
          exportToken: true
          path: gh-actions
          secrets: |
            secret/data/gh-demo demo_secret | DEMO_SECRET ;
      - name: Get secrets 2
        id: secrets2
        uses: hashicorp/vault-action@v2.5.0
        run: |
          vault -version
