name: Github, Vault and TFC Demo

on:
  push:
    tags:
      - "v[0-9]"

jobs:
  demo:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to vault
        id: vault
        uses: hashicorp/vault-action@v2.5.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          role: demo-role
          method: jwt
          namespace: admin
          exportToken: true
          path: gh-actions
          secrets: |
            secret/data/gh-demo demo_secret | DEMO_SECRET ;

      - name: Install Vault CLI
        uses: innovationnorway/setup-vault@v1
        with:
          version: '~1.13'
      
      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v2
      
      - name: Run Terraform
        run: |
          export VAULT_ADDR=${{ secrets.VAULT_ADDR }} ; 
          export VAULT_NAMESPACE=admin ;

          vault status;
          echo;

          vault token lookup;
          echo;

          RESULT=$(vault read azure/creds/gh-demo -format=json) ;
          export ARM_CLIENT_ID=$(echo $RESULT | jq -r .data.client_id) ;
          export ARM_CLIENT_SECRET=$(echo $RESULT | jq -r .data.client_secret) ;
          export ARM_TENANT_ID="4cbbeb38-1769-40b9-8585-b9ee5db09550" ;
          export ARM_SUBSCRIPTION_ID="4a1111dc-eb6e-4f7a-bc4f-b547b202cc2d" ;
          echo;

          ls -l ;
          echo;

          terraform init ;
          terraform plan ;
          terraform apply -auto-approve ;
